site_name: VisVib：トーンチャイム→光/映像変換デバイス
site_url: https://ccbtokyo.github.io/visvib-manual/
repo_url: https://github.com/ccbtokyo/visvib-manual/
docs_dir: 'docs'
nav:
  - Home: 'README.md'
  - Preparation:
      - Hardware:
          - Preparation/Hardware/index.md
          - Preparation/Hardware/make-contact-microphone.md
      - Software:
          - Preparation/Software/index.md
  - Setup: Setup/index.md
  - Usage: Usage/index.md
  - Troubleshooting: Troubleshooting/index.md

copyright: '©2024 AMC Connect AMC + CCBT + Tokyo Bunka Kaikan'

extra_css:
  - css/iframe.css

theme:
  name: material
  favicon: img/favicon.svg
  language: ja
  features:
    #    - navigation.indexes
    - navigation.expand
    - header.autohide
    - search.suggest
    - search.highlight
    - md_in_html
  palette:
    scheme: default
    primary: black
  font:
    text: Noto Sans JP
    code: M PLUS 1 Code

markdown_extensions:
  - mdx_truly_sane_lists:
      nested_indent: 2
  - nl2br
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - footnotes
  - codehilite:
      noclasses: true
      pygments_style: colorful
      linenums: true

plugins:
  - search
  - callouts
  - i18n:
      docs_structure: suffix
      languages:
        - locale: ja
          name: 日本語
          build: true
          default: true
          nav_translations:
            Home: ホーム
            Preparation: 準備
            Hardware: ハードウェア
            Software: ソフトウェア
            Setup: セットアップ
            Usage: 使い方
            Troubleshooting: トラブルシューティング
        - locale: en
          name: English
          build: true
          site_name: 'VisVib: Tone Chime to Light/Video Conversion Device'
